bin = true

[packages.bin]
section = "utils"
branch = "stable"
authors = "Elias Mörz <elias.moerz@mail.de>"
summary = "Syslog-Server Project in Rust"
description = """
A small automation project to set up a syslog server, which also serves as a playground for Rust.
"""

# Falls du auch eine Library-Version (für andere Devs) veröffentlichst:
[packages.lib]
section = "rust"

[copyright]
authors = "Elias Mörz <elias.moerz@mail.de>"
